In [1]:
import numpy as np # to operate algebriac operations
import pandas as pd # to form dataFrames
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for data visualization
from sklearn.preprocessing import LabelEncoder  #string to integer conversion
from sklearn.model_selection import train_test_split #for selection of model to train
from sklearn.linear_model import LinearRegression # to do prediction of data

In [2]:
data = pd.read_csv('/kaggle/input/census-project-dataset/census_income.csv')

In [ ]:
data.shape

(32561, 15)

In [4]:
data.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country          
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [5]:
data = pd.read_csv('/kaggle/input/census-project-dataset/census_income.csv',skipinitialspace = True) #empty column is named as Unnamed after removing the space. 
data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country Unnamed: 14  
0              2174             0              40  United-States       <=50K  
1                 0             0              13  United-States       <=50K  
2                 0             0              40  United-States       <=50K  
3                 0             0              40  United-States       <=50K  
4                 0             0              40           Cuba       <=50K  
...             ...           ...             ...            ...         ...  
32556             0             0              38  United-States       <=50K  
32557             0             0              40  United-States        >50K  
32558             0             0              40  United-States       <=50K  
32559             0             0              20  United-States       <=50K  
32560         15024             0              40  United-States        >50K  

[32561 rows x 15 columns]

In [6]:
data = data.rename(columns = {'Unnamed: 14' : 'Annual Income'})

In [7]:
data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country Annual Income  
0              2174             0              40  United-States         <=50K  
1                 0             0              13  United-States         <=50K  
2                 0             0              40  United-States         <=50K  
3                 0             0              40  United-States         <=50K  
4                 0             0              40           Cuba         <=50K  
...             ...           ...             ...            ...           ...  
32556             0             0              38  United-States         <=50K  
32557             0             0              40  United-States          >50K  
32558             0             0              40  United-States         <=50K  
32559             0             0              20  United-States         <=50K  
32560         15024             0              40  United-States          >50K  

[32561 rows x 15 columns]

In [8]:
data.isin(['?']).sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
Annual Income        0
dtype: int64

In [9]:
data = data.replace('?', np.nan)
data.head(500)

age         workclass  fnlwgt     education  education-num  \
0     39         State-gov   77516     Bachelors             13   
1     50  Self-emp-not-inc   83311     Bachelors             13   
2     38           Private  215646       HS-grad              9   
3     53           Private  234721          11th              7   
4     28           Private  338409     Bachelors             13   
..   ...               ...     ...           ...            ...   
495   41           Private  343121       HS-grad              9   
496   20           Private  262749  Some-college             10   
497   23           Private  403107       5th-6th              3   
498   26           Private   64293  Some-college             10   
499   72               NaN  303588       HS-grad              9   

         marital-status         occupation   relationship   race     sex  \
0         Never-married       Adm-clerical  Not-in-family  White    Male   
1    Married-civ-spouse    Exec-managerial        Husband  White    Male   
2              Divorced  Handlers-cleaners  Not-in-family  White    Male   
3    Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4    Married-civ-spouse     Prof-specialty           Wife  Black  Female   
..                  ...                ...            ...    ...     ...   
495            Divorced       Adm-clerical      Unmarried  White  Female   
496       Never-married  Machine-op-inspct      Own-child  White    Male   
497       Never-married      Other-service      Own-child  White    Male   
498       Never-married     Prof-specialty  Not-in-family  White  Female   
499  Married-civ-spouse                NaN        Husband  White    Male   

     capital-gain  capital-loss  hours-per-week native-country Annual Income  
0            2174             0              40  United-States         <=50K  
1               0             0              13  United-States         <=50K  
2               0             0              40  United-States         <=50K  
3               0             0              40  United-States         <=50K  
4               0             0              40           Cuba         <=50K  
..            ...           ...             ...            ...           ...  
495             0             0              36  United-States         <=50K  
496             0             0              40  United-States         <=50K  
497             0             0              40    El-Salvador         <=50K  
498             0             0              35  United-States         <=50K  
499             0             0              20  United-States         <=50K  

[500 rows x 15 columns]

In [10]:
data = data.dropna()
data

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country Annual Income  
0              2174             0              40  United-States         <=50K  
1                 0             0              13  United-States         <=50K  
2                 0             0              40  United-States         <=50K  
3                 0             0              40  United-States         <=50K  
4                 0             0              40           Cuba         <=50K  
...             ...           ...             ...            ...           ...  
32556             0             0              38  United-States         <=50K  
32557             0             0              40  United-States          >50K  
32558             0             0              40  United-States         <=50K  
32559             0             0              20  United-States         <=50K  
32560         15024             0              40  United-States          >50K  

[30162 rows x 15 columns]

In [11]:
#DAta Manipulation

In [12]:
#a

census_ed = data[['education']]
census_ed

education
0       Bachelors
1       Bachelors
2         HS-grad
3            11th
4       Bachelors
...           ...
32556  Assoc-acdm
32557     HS-grad
32558     HS-grad
32559     HS-grad
32560     HS-grad

[30162 rows x 1 columns]

In [13]:
#b
census_seq = data.loc[:,'age':'relationship']
census_seq

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship  
0           Never-married       Adm-clerical  Not-in-family  
1      Married-civ-spouse    Exec-managerial        Husband  
2                Divorced  Handlers-cleaners  Not-in-family  
3      Married-civ-spouse  Handlers-cleaners        Husband  
4      Married-civ-spouse     Prof-specialty           Wife  
...                   ...                ...            ...  
32556  Married-civ-spouse       Tech-support           Wife  
32557  Married-civ-spouse  Machine-op-inspct        Husband  
32558             Widowed       Adm-clerical      Unmarried  
32559       Never-married       Adm-clerical      Own-child  
32560  Married-civ-spouse    Exec-managerial           Wife  

[30162 rows x 8 columns]

In [14]:
#or
census_seq = data.iloc[:,0:8]
census_seq

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship  
0           Never-married       Adm-clerical  Not-in-family  
1      Married-civ-spouse    Exec-managerial        Husband  
2                Divorced  Handlers-cleaners  Not-in-family  
3      Married-civ-spouse  Handlers-cleaners        Husband  
4      Married-civ-spouse     Prof-specialty           Wife  
...                   ...                ...            ...  
32556  Married-civ-spouse       Tech-support           Wife  
32557  Married-civ-spouse  Machine-op-inspct        Husband  
32558             Widowed       Adm-clerical      Unmarried  
32559       Never-married       Adm-clerical      Own-child  
32560  Married-civ-spouse    Exec-managerial           Wife  

[30162 rows x 8 columns]

In [15]:
#c

census_col = data.iloc[:,[5,8,11]]
census_col

marital-status   race  capital-loss
0           Never-married  White             0
1      Married-civ-spouse  White             0
2                Divorced  White             0
3      Married-civ-spouse  Black             0
4      Married-civ-spouse  Black             0
...                   ...    ...           ...
32556  Married-civ-spouse  White             0
32557  Married-civ-spouse  White             0
32558             Widowed  White             0
32559       Never-married  White             0
32560  Married-civ-spouse  White             0

[30162 rows x 3 columns]

In [16]:
#d
data.columns


Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'Annual Income'],
      dtype='object')

In [17]:
male_gov = data[(data['sex']== 'Male') & (data['workclass']== 'State-gov')]

In [18]:
male_gov.shape #shape is a tuple hence , n0t callable.
#do not use brackets after shape

(795, 15)

In [19]:
#e

census_us = data[(data['age']==39) & ((data['education']=='Bachelors') | (data['native-country']=='United-States'))]

In [20]:
census_us

age         workclass  fnlwgt     education  education-num  \
0       39         State-gov   77516     Bachelors             13   
28      39           Private  367260       HS-grad              9   
129     39           Private  365739  Some-college             10   
166     39       Federal-gov  235485    Assoc-acdm             12   
320     39  Self-emp-not-inc  174308       HS-grad              9   
...    ...               ...     ...           ...            ...   
32146   39           Private  117381  Some-college             10   
32260   39       Federal-gov  232036  Some-college             10   
32428   39       Federal-gov  110622     Bachelors             13   
32468   39  Self-emp-not-inc  193689       HS-grad              9   
32545   39         Local-gov  111499    Assoc-acdm             12   

           marital-status        occupation   relationship  \
0           Never-married      Adm-clerical  Not-in-family   
28               Divorced   Exec-managerial  Not-in-family   
129              Divorced      Craft-repair  Not-in-family   
166         Never-married   Exec-managerial  Not-in-family   
320    Married-civ-spouse   Exec-managerial        Husband   
...                   ...               ...            ...   
32146            Divorced  Transport-moving  Not-in-family   
32260  Married-civ-spouse      Adm-clerical        Husband   
32428  Married-civ-spouse      Adm-clerical           Wife   
32468       Never-married   Exec-managerial  Not-in-family   
32545  Married-civ-spouse      Adm-clerical           Wife   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
0                   White    Male          2174             0              40   
28                  White    Male             0             0              80   
129                 White    Male             0             0              40   
166                 White    Male             0             0              42   
320                 White    Male             0             0              40   
...                   ...     ...           ...           ...             ...   
32146               White    Male             0             0              65   
32260               White    Male             0             0              40   
32428  Asian-Pac-Islander  Female             0             0              40   
32468               White    Male             0             0              65   
32545               White  Female             0             0              20   

      native-country Annual Income  
0      United-States         <=50K  
28     United-States         <=50K  
129    United-States         <=50K  
166    United-States         <=50K  
320    United-States         <=50K  
...              ...           ...  
32146  United-States         <=50K  
32260  United-States          >50K  
32428    Philippines         <=50K  
32468  United-States         <=50K  
32545  United-States          >50K  

[742 rows x 15 columns]

In [21]:
#f
#to choose random values from the dataset use sample command.
census_200 = data.sample(200, random_state = 2)
census_200

#random state freeze the values of data or rows that are selected
#same rows in output everytime we run the cell.

age  workclass  fnlwgt     education  education-num  \
28959   33    Private   69727       7th-8th              4   
3270    73    Private  123160          10th              6   
9680    29    Private  115677     Bachelors             13   
24430   38    Private  193372  Some-college             10   
10240   29    Private  162002       HS-grad              9   
...    ...        ...     ...           ...            ...   
11584   53    Private  171924     Bachelors             13   
2044    53    Private  274528     Bachelors             13   
16943   36    Private  200360  Some-college             10   
22768   53  Local-gov   82783       HS-grad              9   
6732    31    Private  595000       HS-grad              9   

           marital-status         occupation    relationship   race     sex  \
28959  Married-civ-spouse    Farming-fishing         Husband  White    Male   
3270              Widowed      Other-service   Not-in-family  White  Female   
9680        Never-married       Tech-support   Not-in-family  White    Male   
24430       Never-married    Exec-managerial       Own-child  White  Female   
10240       Never-married      Other-service       Own-child  White  Female   
...                   ...                ...             ...    ...     ...   
11584            Divorced     Prof-specialty   Not-in-family  White    Male   
2044             Divorced    Exec-managerial   Not-in-family  White    Male   
16943       Never-married       Craft-repair   Not-in-family  White    Male   
22768            Divorced    Exec-managerial   Not-in-family  White    Male   
6732        Never-married  Handlers-cleaners  Other-relative  Black  Female   

       capital-gain  capital-loss  hours-per-week native-country Annual Income  
28959             0             0              40         Mexico         <=50K  
3270              0             0              10  United-States         <=50K  
9680              0             0              40  United-States         <=50K  
24430             0             0              40  United-States         <=50K  
10240             0             0              35  United-States         <=50K  
...             ...           ...             ...            ...           ...  
11584         14344             0              55  United-States          >50K  
2044              0             0              70  United-States         <=50K  
16943             0             0              40  United-States         <=50K  
22768             0             0              40  United-States         <=50K  
6732              0             0              35  United-States         <=50K  

[200 rows x 15 columns]

In [22]:
#g
data['workclass'].value_counts()

Private             22286
Self-emp-not-inc     2499
Local-gov            2067
State-gov            1279
Self-emp-inc         1074
Federal-gov           943
Without-pay            14
Name: workclass, dtype: int64

In [23]:
data.workclass.value_counts()

Private             22286
Self-emp-not-inc     2499
Local-gov            2067
State-gov            1279
Self-emp-inc         1074
Federal-gov           943
Without-pay            14
Name: workclass, dtype: int64

In [24]:
#h

data.groupby(['workclass'])[['capital-gain']].mean().sort_values(by= 'capital-gain' ,ascending= True)

capital-gain
workclass                     
Without-pay         487.857143
State-gov           684.306489
Local-gov           829.230285
Federal-gov         832.321315
Private             879.858207
Self-emp-not-inc   1913.134454
Self-emp-inc       4810.746741

In [25]:
#i

data1 = data[(data['Annual Income']=='>50K')]
data1

age         workclass  fnlwgt     education  education-num  \
7       52  Self-emp-not-inc  209642       HS-grad              9   
8       31           Private   45781       Masters             14   
9       42           Private  159449     Bachelors             13   
10      37           Private  280464  Some-college             10   
11      30         State-gov  141297     Bachelors             13   
...    ...               ...     ...           ...            ...   
32538   38           Private  139180     Bachelors             13   
32545   39         Local-gov  111499    Assoc-acdm             12   
32554   53           Private  321865       Masters             14   
32557   40           Private  154374       HS-grad              9   
32560   52      Self-emp-inc  287927       HS-grad              9   

           marital-status         occupation   relationship  \
7      Married-civ-spouse    Exec-managerial        Husband   
8           Never-married     Prof-specialty  Not-in-family   
9      Married-civ-spouse    Exec-managerial        Husband   
10     Married-civ-spouse    Exec-managerial        Husband   
11     Married-civ-spouse     Prof-specialty        Husband   
...                   ...                ...            ...   
32538            Divorced     Prof-specialty      Unmarried   
32545  Married-civ-spouse       Adm-clerical           Wife   
32554  Married-civ-spouse    Exec-managerial        Husband   
32557  Married-civ-spouse  Machine-op-inspct        Husband   
32560  Married-civ-spouse    Exec-managerial           Wife   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
7                   White    Male             0             0              45   
8                   White  Female         14084             0              50   
9                   White    Male          5178             0              40   
10                  Black    Male             0             0              80   
11     Asian-Pac-Islander    Male             0             0              40   
...                   ...     ...           ...           ...             ...   
32538               Black  Female         15020             0              45   
32545               White  Female             0             0              20   
32554               White    Male             0             0              40   
32557               White    Male             0             0              40   
32560               White  Female         15024             0              40   

      native-country Annual Income  
7      United-States          >50K  
8      United-States          >50K  
9      United-States          >50K  
10     United-States          >50K  
11             India          >50K  
...              ...           ...  
32538  United-States          >50K  
32545  United-States          >50K  
32554  United-States          >50K  
32557  United-States          >50K  
32560  United-States          >50K  

[7508 rows x 15 columns]

In [26]:
#j

d1= len((data[(data['native-country']=='United-States') & (data['workclass'] == 'Private') & (data['Annual Income'] == '<=50K')]))

percentage= (d1 / len(data[data['native-country']=='United-States'])) * 100
percentage

56.697207678883075

In [27]:
#OR
#without using len() we can write .shape[0] which gives the no. of rows

data2 = data[(data['native-country'] == 'United-States')]
(data2[(data2['workclass']=='Private')&(data['Annual Income'] == '<=50K')].shape[0]/data2.shape[0])*100

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """


56.697207678883075

In [28]:
#k
data['marital-status'].value_counts()

Married-civ-spouse       14065
Never-married             9726
Divorced                  4214
Separated                  939
Widowed                    827
Married-spouse-absent      370
Married-AF-spouse           21
Name: marital-status, dtype: int64

In [29]:
l = ['Married-civ-spouse','Married-spouse-absent', 'Married-AF-spouse']
c = 0
for i in l:
    c+=data['marital-status'].value_counts()[i]
(c/data.shape[0])*100

47.92785624295471

In [30]:
data['marital-status'].value_counts()['Married-spouse-absent']

370

In [31]:
#L

grad = data[(data['education']=='HS-grad') & (data['Annual Income']=='>50K')].shape

In [32]:
grad

(1617, 15)

In [33]:
(grad[0]/data[(data['education']=='HS-grad')].shape[0]) * 100

16.432926829268293

# Linear Regression Model fitting

In [34]:
x = pd.DataFrame(data['education-num'])
y = pd.DataFrame(data['hours-per-week'])

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 42)

In [36]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(21113, 1)
(9049, 1)
(21113, 1)
(9049, 1)


In [37]:
LR = LinearRegression()

In [38]:
LR.fit(x_train,y_train)

LinearRegression()

In [39]:
y_pred = LR.predict(x_test)

In [40]:
y_pred

array([[44.30810976],
       [40.20968024],
       [40.20968024],
       ...,
       [42.94196659],
       [40.20968024],
       [42.94196659]])

In [41]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_error

In [42]:
mse = mean_squared_error

In [43]:
mse1= mse(y_test,y_pred)
mse1

137.81263845871413

In [44]:
rmse = np.sqrt(mse1)
rmse

11.73936277907426

# Logistic Regression Model Fitting

## simple Logistic regression

In [45]:
from sklearn.linear_model import LogisticRegression 

In [46]:
x1 = data['occupation']
y1 = data['Annual Income']

In [47]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()  #used to convert string data into numeric values.

In [48]:
x1 = LE.fit_transform(x1)
y1 = LE.fit_transform(y1)

In [49]:
x1 = pd.DataFrame(x1)
y1 = pd.DataFrame(y1)

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
from sklearn import model_selection

In [52]:
#dir(model_selection)

In [53]:
x_train,x_test,y_train,y_test = train_test_split(x1,y1,train_size = 0.65 , random_state = 10)

In [54]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(19605, 1)
(10557, 1)
(19605, 1)
(10557, 1)


In [55]:
LG_model = LogisticRegression()

In [56]:
import warnings
warnings.filterwarnings('ignore')

In [57]:
LG_model.fit(x_train,y_train)

LogisticRegression()

In [58]:
y_pred = LG_model.predict(x_test)

In [59]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [61]:
cf= confusion_matrix(y_test,y_pred)
cf

array([[7903,    0],
       [2654,    0]])

In [62]:
acc = accuracy_score(y_test,y_pred)
acc

0.7486028227716207

## Multiple Logistic regression

In [63]:
x2 = data[['age','workclass','education']]
y2 = data['Annual Income']

In [64]:
x2.head()

age         workclass  education
0   39         State-gov  Bachelors
1   50  Self-emp-not-inc  Bachelors
2   38           Private    HS-grad
3   53           Private       11th
4   28           Private  Bachelors

In [65]:
data['age'] = LE.fit_transform(data['age'])
data['workclass'] = LE.fit_transform(data['workclass'])
data['education'] = LE.fit_transform(data['education'])
data['Annual Income'] = LE.fit_transform(data['Annual Income'])


In [66]:
x2 = data[['age','workclass','education']]
y2 = data['Annual Income']

In [67]:
x2.head()

age  workclass  education
0   22          5          9
1   33          4          9
2   21          2         11
3   36          2          1
4   11          2          9

In [68]:
x_train,x_test,y_train,y_test = train_test_split(x2,y2,test_size = 0.2, random_state = 32)

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
LOG = LogisticRegression()

In [71]:
LOG.fit(x_train,y_train)

LogisticRegression()

In [72]:
y_pred= LOG.predict(x_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [73]:
cf1 = confusion_matrix(y_pred,y_test)
cf1

array([[4432, 1392],
       [ 151,   58]])

In [74]:
acc1 = accuracy_score(y_pred,y_test)
acc1

0.7442400132604011

# Decision Tree Model Fitting

In [75]:
x3 = data.drop(['Annual Income'], axis = 1)
y3 = data['Annual Income']

In [76]:
print(x3.shape)
print(y3.shape)

(30162, 14)
(30162,)


In [77]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'Annual Income'],
      dtype='object')

In [78]:
col_list = list(x3.columns)

In [79]:
x3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             30162 non-null  int64 
 1   workclass       30162 non-null  int64 
 2   fnlwgt          30162 non-null  int64 
 3   education       30162 non-null  int64 
 4   education-num   30162 non-null  int64 
 5   marital-status  30162 non-null  object
 6   occupation      30162 non-null  object
 7   relationship    30162 non-null  object
 8   race            30162 non-null  object
 9   sex             30162 non-null  object
 10  capital-gain    30162 non-null  int64 
 11  capital-loss    30162 non-null  int64 
 12  hours-per-week  30162 non-null  int64 
 13  native-country  30162 non-null  object
dtypes: int64(8), object(6)
memory usage: 4.5+ MB


In [80]:
col_list

['age',
 'workclass',
 'fnlwgt',
 'education',
 'education-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'native-country']

In [81]:
for i in col_list:
    x3[i].dtypes == 'object'
    x3[i] = LE.fit_transform(x3[i])

In [82]:
x3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30162 non-null  int64
 1   workclass       30162 non-null  int64
 2   fnlwgt          30162 non-null  int64
 3   education       30162 non-null  int64
 4   education-num   30162 non-null  int64
 5   marital-status  30162 non-null  int64
 6   occupation      30162 non-null  int64
 7   relationship    30162 non-null  int64
 8   race            30162 non-null  int64
 9   sex             30162 non-null  int64
 10  capital-gain    30162 non-null  int64
 11  capital-loss    30162 non-null  int64
 12  hours-per-week  30162 non-null  int64
 13  native-country  30162 non-null  int64
dtypes: int64(14)
memory usage: 4.5 MB


In [83]:
x3.head()

age  workclass  fnlwgt  education  education-num  marital-status  \
0   22          5    2491          9             12               4   
1   33          4    2727          9             12               2   
2   21          2   13188         11              8               0   
3   36          2   14354          1              6               2   
4   11          2   18120          9             12               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           0             1     4    1            24             0   
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   
4           9             5     2    0             0             0   

   hours-per-week  native-country  
0              39              38  
1              12              38  
2              39              38  
3              39              38  
4              39               4

In [84]:
x_train,x_test,y_train,y_test = train_test_split(x3,y3,test_size = 0.3, random_state = 42)

In [85]:
from sklearn.tree import DecisionTreeClassifier

In [86]:
DTC = DecisionTreeClassifier()

In [87]:
DTC.fit(x_train,y_train)

DecisionTreeClassifier()

In [88]:
y_pred  = DTC.predict(x_test)
y_pred

array([0, 1, 0, ..., 1, 0, 0])

In [89]:
cf3 = confusion_matrix(y_pred,y_test)
cf3

array([[5888,  885],
       [ 879, 1397]])

In [90]:
acc3 = accuracy_score(y_pred,y_test)
acc3

0.8050613327439496

#  Random Forest Model Fitting

In [91]:
x4 = x3
y4 = y3

In [92]:
x4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30162 non-null  int64
 1   workclass       30162 non-null  int64
 2   fnlwgt          30162 non-null  int64
 3   education       30162 non-null  int64
 4   education-num   30162 non-null  int64
 5   marital-status  30162 non-null  int64
 6   occupation      30162 non-null  int64
 7   relationship    30162 non-null  int64
 8   race            30162 non-null  int64
 9   sex             30162 non-null  int64
 10  capital-gain    30162 non-null  int64
 11  capital-loss    30162 non-null  int64
 12  hours-per-week  30162 non-null  int64
 13  native-country  30162 non-null  int64
dtypes: int64(14)
memory usage: 4.5 MB


In [93]:
x_train,x_test,y_train,y_test = train_test_split(x4,y4,test_size = 0.2, random_state = 42)

In [94]:
from sklearn.ensemble import RandomForestClassifier

In [95]:
RFC = RandomForestClassifier(n_estimators=300)  #parametric constructor 

#by default 100 estimators if we do not define any value

In [96]:
RFC.fit(x_train,y_train)

RandomForestClassifier(n_estimators=300)

In [97]:
y_pred = RFC.predict(x_test)
y_pred

array([0, 0, 0, ..., 1, 1, 0])

In [98]:
cf4 = confusion_matrix(y_pred,y_test)
cf4

array([[4165,  536],
       [ 338,  994]])

In [99]:
acc4 = accuracy_score(y_pred,y_test)
acc4

0.85513011768606

In [100]:
from sklearn.metrics import classification_report

In [101]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.92      0.91      4503
           1       0.75      0.65      0.69      1530

    accuracy                           0.86      6033
   macro avg       0.82      0.79      0.80      6033
weighted avg       0.85      0.86      0.85      6033

